### ISSUE TITLE
URL does not exist for MPII Pose dataset

### ISSUE THREAD

**Issue by dikshant2210** [dbcollection/dbcollection#147]
loading the mpii dataset gives url does not exist error. I was able to fix it by changing the allow_redirections parameter to True in requests.head in utils/url.py check_url_exists function.

**Comment by farrajota** [comment]
Thank you. I'll take a look at it as soon as possible to fix this.

**Comment by farrajota** [comment]
This issue should be fixed in `v0.2.4`. If this issue persist, respond in this issue and I'll take another look at it.
