### ISSUE TITLE
Missing requirements.txt file in repo; install from source doesn't work

### ISSUE THREAD

**Issue by dtch1997** [dbcollection/dbcollection#188]
The repository cannot be installed from source due to missing requirements.txt in the repository.

**Comment by sanlauf** [comment]
!!!!Issue still exists!!!!

Fixing it isn`t an option?

**Comment by Shadowwalker10** [comment]
issue persists

**Comment by sumeetkr13** [comment]
Is there any update here?
I am unable to install the library on Apple M1 Mac in a virtual environment Python 3.9.5

**Comment by pranoyr** [comment]
+1

**Comment by farrajota** [comment]
Hi. I've found some time to take a look at this and pushed the `requirements.txt` file missing in #201 .

Apologies for taking so long.
